MainWidget:

#:set btn_font_h 30

<MainWidget>:
    orientation: 'vertical'
    Label:
        color: 0, 0, 0, 1
        text: root.total
        font_name: "resources/digital-7.ttf"
        font_size: "80dp"
        size_hint: 1, 1/3
    Label:
        id: input
        text: root.equation
        color: 0, 0, 0, 0.75
        font_size: "30dp"
        size_hint: 1, 1/3
    ComputeBox:
        size_hint: 1, 1/2
        BoxLayout:
            orientation: 'vertical'
            size_hint: 3/5, 1
            NumButtons:
                id: num_buttons
                text: self.text
        BoxLayout:
            orientation: 'vertical'
            size_hint: 2/5, 1
            padding: 20
            spacing: 10
            MathButtons:
                id: math_buttons
