MainWidget:

<MainWidget>:
    orientation: 'vertical'
    Widget:
        id: wid
        color: 1, 1, 1, 0
        canvas.before:
            Rectangle:
                pos: root.pos
                size: root.size
        Label:
            pos: wid.pos
            size: wid.width, wid.height
            color: 0, 0, 0, 1
            text: root.total
            font_name: "resources/digital-7.ttf"
            font_size: 80
    TextInput:
        id: input
        halign: 'center'
        input_filter: 'int'
        size_hint: 1, 1/2
        text: ""
        multiline: False
        on_text_validate: root.enter
    BoxLayout:
        Button:
            text: "+"
            color: 1, 1, 1, 1
            on_press: root.add_number(input)
        Button:
            text: "Enter"
            color: 1, 1, 1, 1
            on_press: root.enter(input)
